### ISSUE TITLE
Unknown function error

### ISSUE THREAD

**Issue by contemplate** [BrianHenryIE/bh-wc-checkout-rate-limiter#11]
We keep getting this error on the admin pages:

```
Checkout Rate Limiter. Error: "Uncaught Error: Call to undefined function BrianHenryIE\Checkout_Rate_Limiter\WooCommerce\wc_get_current_admin_url() in /chroot/home/server_name_removed/html/wp-content/plugins/bh-wc-checkout-rate-limiter/WooCommerce/class-settings-payments.php:59

Stack trace:

#0 /chroot/home/server_name_removed/html/wp-includes/class-wp-hook.php(307): BrianHenryIE\Checkout_Rate_Limiter\WooCommerce\Settings_Payments->record_page_visit_time(Object(WP_Screen))

#1 /chroot/home/server_name_removed/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)

#2 /chroot/home/server_name_removed/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)

#3 /chroot/home/server_name_removed/html/wp-admin/includes/class-wp-screen.php(422): do_action('current_screen', Object(WP_Screen))

#4 /chroot/home/server_name_removed/html/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()

#5 /chroot/home/server_name_removed/html/wp-content/plugins" at 2022-10-11T03:02:39Z UTC.
```

**Comment by BrianHenryIE** [comment]
That was a rookie mistake by me, I used a WooCommerce function on a general WordPress hook, without checking was WooCommerce active/did the function exist.
