### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by hypercolors** [BrianHenryIE/bh-wc-checkout-rate-limiter#24]
Fatal Error:
```
Stack trace:
#0 /home/customer/www/domain.com/public_html/wp-content/plugins/bh-wc-checkout-rate-limiter/vendor-prefixed/wp-oop/transient-cache/src/CachePool.php(137): BrianHenryIE\Checkout_Rate_Limiter\WpOop\TransientCache\CachePool->setTransient('checkout/checko...', Array, 60)
#1 /home/customer/www/domain.com/public_html/wp-content/plugins/bh-wc-checkout-rate-limiter/vendor-prefixed/nikolaposa/rate-limit/src/Psr16RateLimiter.php(129): BrianHenryIE\Checkout_Rate_Limiter\WpOop\TransientCache\CachePool->set('checkout/checko...', Array, 60)
#2 /home/customer/www/domain.com/public_html/wp-content/plugins/bh-wc-checkout-rate-limiter/vendor-prefixed/nikolaposa/rate-limit/src/Psr16RateLimiter.php(59): BrianHenryIE\Checkout_Rate
{"type":1,"message":"Uncaught RuntimeException: set_transient() failed with key \"checkout\/checkout74.80.182.73-60\" with TTL 60s in \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php:322\nStack trace:\n#0 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php(137): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->setTransient('checkout\/checko...', Array, 60)\n#1 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(129): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->set('checkout\/checko...', Array, 60)\n#2 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(59): BrianHenryIE\\Checkout_Rate","file":"\/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php","line":140,"debug_backtrace":[{"file":"\/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php","lineNumber":80,"arguments":["error","Uncaught RuntimeException: set_transient() failed with key \"checkout\/checkout74.80.182.73-60\" with TTL 60s in \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php:322\nStack trace:\n#0 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php(137): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->setTransient('checkout\/checko...', Array, 60)\n#1 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(129): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->set('checkout\/checko...', Array, 60)\n#2 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(59): BrianHenryIE\\Checkout_Rate",{"type":1,"message":"Uncaught RuntimeException: set_transient() failed with key \"checkout\/checkout74.80.182.73-60\" with TTL 60s in \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php:322\nStack trace:\n#0 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php(137): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->setTransient('checkout\/checko...', Array, 60)\n#1 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(129): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->set('checkout\/checko...', Array, 60)\n#2 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(59): BrianHenryIE\\Checkout_Rate","file":"\/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php","line":140}],"applicationFrame":true,"method":"log","class":"BrianHenryIE\\Checkout_Rate_Limiter\\WP_Logger\\API\\BH_WP_PSR_Logger"},{"file":"\/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php","lineNumber":52,"arguments":["Uncaught RuntimeException: set_transient() failed with key \"checkout\/checkout74.80.182.73-60\" with TTL 60s in \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php:322\nStack trace:\n#0 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php(137): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->setTransient('checkout\/checko...', Array, 60)\n#1 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(129): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->set('checkout\/checko...', Array, 60)\n#2 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(59): BrianHenryIE\\Checkout_Rate",{"type":1,"message":"Uncaught RuntimeException: set_transient() failed with key \"checkout\/checkout74.80.182.73-60\" with TTL 60s in \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php:322\nStack trace:\n#0 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php(137): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->setTransient('checkout\/checko...', Array, 60)\n#1 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(129): BrianHenryIE\\Checkout_Rate_Limiter\\WpOop\\TransientCache\\CachePool->set('checkout\/checko...', Array, 60)\n#2 \/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/nikolaposa\/rate-limit\/src\/Psr16RateLimiter.php(59): BrianHenryIE\\Checkout_Rate","file":"\/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/wp-oop\/transient-cache\/src\/CachePool.php","line":140}],"applicationFrame":true,"method":"error","class":"BrianHenryIE\\Checkout_Rate_Limiter\\WP_Logger\\API\\BH_WP_PSR_Logger"},{"file":"\/home\/customer\/www\/domain.com\/public_html\/wp-content\/plugins\/bh-wc-checkout-rate-limiter\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/php\/class-php-shutdown-handler.php","lineNumber":87,"arguments":[],"applicationFrame":true,"method":"handle","class":"BrianHenryIE\\Checkout_Rate_Limiter\\WP_Logger\\PHP\\PHP_Shutdown_Handler"},{"file":"unknown","lineNumber":0,"arguments":[],"applicationFrame":false,"method":"[top]","class":null}],"filters":["template_redirect","wc_ajax_checkout"]}
```

**Comment by danielshields** [comment]
I also received this error on WP Engine, after installing the plugin and clearing the server cache. Happy to provide more details, if helpful. I suspect WP Engine's caching layer is interfering with something in the plugin, so perhaps certain URLs should be excluded from the cache.

**Comment by BrianHenryIE** [comment]
It's inserting a plain PHP array into the cache, so maybe it's the cache key that's the problem. What's the cache engine? (Redis/Memcached/...)

**Comment by danielshields** [comment]
My understanding is WP Engine uses Redis for page cache, and Memcached for its object caching.
